name: crypto_wallet_util
description: A collection of utility functions for cryptocurrencies.
version: 1.2.0
homepage: https://github.com/fxwalletOfficial/fx-wallet-packages/tree/main/packages/wallet_crypto_util

environment:
  sdk: '>=2.17.0 <4.0.0'

dependency_overrides:
  pointycastle: ^4.0.0

dependencies:
  bip340: ^0.3.1
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  bs58check: ^1.0.2
  ed25519_hd_key: ^2.3.0
  equatable: ^2.0.7
  fixnum: ^1.1.1
  hex: ^0.2.0
  json_annotation: ^4.9.0
  pinenacl: ^0.6.0
  pointycastle: ^4.0.0
  protobuf: ^4.2.0
  sr25519: ^0.7.1
  ss58: ^1.1.2
  substrate_bip39: ^0.7.1
  base32: ^2.2.0
  secp256k1_ecdsa: ^0.6.2
  buffer: ^1.2.3
  bech32m_i: ^0.2.2
  decimal: ^3.2.4
  blockchain_utils: ^1.4.1

dev_dependencies:
  test: ^1.6.2
