name: bc_ur_dart
description: A dart plugin for Uniform Resources(URs) decode/encode. URs are URI-encoded CBOR structures developed by Blockchain Commons.
version: 0.1.21
homepage: https://github.com/fxwalletOfficial/fx-wallet-packages/tree/main/packages/bc_ur_dart

environment:
  sdk: ^3.3.4

dependency_overrides:
  pointycastle: ^4.0.0

dependencies:
  cbor: ^6.3.7
  convert: ^3.1.2
  crypto: ^3.0.6
  crypto_wallet_util: ^1.2.0
  uuid: ^4.4.0
  xrandom: ^0.7.2

dev_dependencies:

  lints: ^3.0.0
  test: ^1.24.0
